import React, { useState, useEffect } from "react";
import { motion } from "motion/react";
import { 
  FileText, Calendar, User, Clock, AlertTriangle, ShieldAlert, 
  Printer, ArrowLeft, Loader2, Pill, Activity, Compass, 
  HeartHandshake, Heart, ShieldQuestion, HelpCircle, Download
} from "lucide-react";
import { ReportSection } from "./ReportSection";

export interface ReportData {
  summary: string;
  symptomsIdentified: string[];
  possibleConditions: string[];
  medicationsSuggested: { name: string; purpose: string; note: string }[];
  recommendations: string[];
  restAdvice: string;
  urgencyLevel: 'low' | 'medium' | 'high';
  followUpAdvise: string;
  disclaimer: string;
}

interface ReportViewScreenProps {
  consultationId: string;
  onBackToDashboard: () => void;
}

export function ReportViewScreen({ consultationId, onBackToDashboard }: ReportViewScreenProps) {
  const [loading, setLoading] = useState<boolean>(true);
  const [error, setError] = useState<string | null>(null);
  const [consultation, setConsultation] = useState<any>(null);
  const [report, setReport] = useState<ReportData | null>(null);

  useEffect(() => {
    let isMounted = true;

    async function fetchAndGenerateReport() {
      try {
        setLoading(true);
        setError(null);

        // Fetch current consultation session state
        const res = await fetch(`/api/consultations/${consultationId}`);
        if (!res.ok) {
          throw new Error("Unable to retrieve consultation details.");
        }
        const data = await res.json();
        
        if (!isMounted) return;
        setConsultation(data);

        // Check if report is already compiled or requires GPT invocation
        if (data.status === "completed" && data.summary) {
          // Parse medications if they are stored as JSON
          let medsList = [];
          try {
            medsList = JSON.parse(data.medications || "[]");
          } catch (e) {
            medsList = [];
          }

          setReport({
            summary: data.summary,
            symptomsIdentified: data.symptoms.split(",").map((s: string) => s.trim()).filter(Boolean),
            possibleConditions: ["Assessed physiological symptoms review"],
            medicationsSuggested: medsList,
            recommendations: (data.recommendations || "").split("\n").filter(Boolean),
            restAdvice: data.restAdvice || "Ensure gentle hydration and relative physical rest cycles.",
            urgencyLevel: data.symptoms.toLowerCase().includes("chest") ? "high" : "medium",
            followUpAdvise: "In case of worsening baseline indicators, contact primary care clinics immediately.",
            disclaimer: "This report is generated by an AI assistant for informational purposes only. It does not constitute medical advice. Please consult a licensed healthcare professional."
          });
          setLoading(false);
        } else {
          // Trigger report compiler API
          const genRes = await fetch("/api/generate-report", {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({
              consultationId,
              transcript: data.transcript || data.symptoms || "Patient requested standard guidance update.",
              doctorType: data.doctorType || "General Physician",
              symptoms: data.symptoms
            })
          });

          if (!genRes.ok) {
            throw new Error("Report compiler timeout or key constraint. Please double-check OpenAI service.");
          }

          const reportJson = await genRes.json();
          if (!isMounted) return;

          setReport(reportJson);
          setLoading(false);
        }
      } catch (err: any) {
        console.error("error compiling dynamic clinician review:", err);
        if (isMounted) {
          setError(err.message || "Failed to finalize consultation report. Check mock fallbacks.");
          setLoading(false);
        }
      }
    }

    fetchAndGenerateReport();

    return () => {
      isMounted = false;
    };
  }, [consultationId]);

  if (loading) {
    return (
      <div className="min-h-screen bg-slate-50 dark:bg-slate-950 flex flex-col items-center justify-center p-6 text-center">
        <div className="relative flex flex-col items-center max-w-md p-8 bg-white dark:bg-slate-900 rounded-3xl border border-slate-200/60 dark:border-slate-800/60 shadow-xl">
          <Loader2 className="h-10 w-10 text-teal animate-spin mb-4" />
          <h3 className="text-xl font-bold text-slate-800 dark:text-slate-100 mb-2">Analyzing Audio Transcript</h3>
          <p className="text-sm text-slate-600 dark:text-slate-400 mb-4">
            MediVoice AI structure engine is assembling diagnostic criteria and cataloging clinical terminology...
          </p>
          <div className="w-full bg-slate-100 dark:bg-slate-800 h-1.5 rounded-full overflow-hidden">
            <div className="bg-teal h-full animate-pulse rounded-full" style={{ width: "80%" }}></div>
          </div>
        </div>
      </div>
    );
  }

  if (error || !report) {
    return (
      <div className="min-h-screen bg-slate-50 dark:bg-slate-950 flex flex-col items-center justify-center p-6 text-center">
        <div className="max-w-md p-8 bg-white dark:bg-slate-900 rounded-3xl border border-rose-100 dark:border-rose-900/30 shadow-xl">
          <AlertTriangle className="h-12 w-12 text-rose-500 mx-auto mb-4" />
          <h3 className="text-lg font-bold text-slate-800 dark:text-slate-100 mb-2">Report Delivery Failure</h3>
          <p className="text-sm text-slate-600 dark:text-slate-400 mb-6">
            {error || "An unexpected glitch delayed report completion."}
          </p>
          <button
            onClick={onBackToDashboard}
            className="px-6 py-2.5 bg-teal hover:bg-teal-dark text-white rounded-xl text-xs font-bold tracking-wider uppercase transition-all shadow-md flex items-center gap-2 mx-auto"
          >
            <ArrowLeft className="h-4 w-4" /> Go Back to Dashboard
          </button>
        </div>
      </div>
    );
  }

  const urgencyLabel = report.urgencyLevel || "low";
  const urgencyColors = {
    low: "bg-emerald-50 text-emerald-700 dark:bg-emerald-950/40 dark:text-emerald-400 border-emerald-200/50 dark:border-emerald-900/30",
    medium: "bg-amber-50 text-amber-700 dark:bg-amber-950/40 dark:text-amber-400 border-amber-200/50 dark:border-amber-900/40",
    high: "bg-rose-50 text-rose-700 dark:bg-rose-950/40 dark:text-rose-400 border-rose-200/50 dark:border-rose-900/30"
  }[urgencyLabel];

  return (
    <div className="min-h-screen bg-slate-50 dark:bg-slate-950 py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-4xl mx-auto space-y-8">
        
        {/* Navigation row */}
        <div className="flex items-center justify-between">
          <button
            onClick={onBackToDashboard}
            className="inline-flex items-center gap-2 text-xs sm:text-sm font-semibold text-slate-500 hover:text-slate-800 dark:text-slate-400 dark:hover:text-slate-200 transition-colors"
          >
            <ArrowLeft className="h-4 w-4" /> Back to Dashboard
          </button>
          
          <div className="flex items-center gap-2">
            <button
              onClick={() => window.print()}
              className="p-2 sm:px-4 sm:py-2 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 text-slate-600 dark:text-slate-350 hover:bg-slate-100 dark:hover:bg-slate-800 rounded-xl text-xs font-semibold tracking-wide flex items-center gap-2 shadow-sm transition-all cursor-pointer"
            >
              <Printer className="h-4 w-4" />
              <span className="hidden sm:inline">Print Report</span>
            </button>
            <button
              disabled
              className="p-2 sm:px-4 sm:py-2 bg-slate-100 dark:bg-slate-950 border border-slate-200/60 dark:border-slate-800/40 text-slate-400/80 rounded-xl text-xs font-semibold tracking-wide flex items-center gap-2 transition-all cursor-not-allowed select-none"
              title="PDF Download integration coming soon"
            >
              <Download className="h-4 w-4" />
              <span className="hidden sm:inline">Download</span>
            </button>
          </div>
        </div>

        {/* TOP SECTION — Report Header Card banner */}
        <motion.div 
          initial={{ opacity: 0, scale: 0.98 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ duration: 0.4 }}
          className="bg-white dark:bg-slate-900 border border-slate-200/60 dark:border-slate-800/60 rounded-3xl p-6 sm:p-8 shadow-sm relative overflow-hidden"
        >
          <div className="absolute right-0 top-0 translate-x-8 -translate-y-8 w-44 h-44 bg-teal/5 dark:bg-teal/10 rounded-full blur-3xl pointers-events-none select-none"></div>
          
          <div className="flex flex-col md:flex-row md:items-center justify-between gap-6">
            <div className="space-y-4">
              <div className="inline-flex items-center gap-2 px-3 py-1 bg-teal/10 dark:bg-teal/25 rounded-full text-teal-700 dark:text-teal-300 text-xs font-extrabold tracking-widest uppercase">
                <FileText className="h-3.5 w-3.5" /> Consultation Complete
              </div>
              
              <h1 className="font-sans font-black text-2xl sm:text-3xl text-slate-900 dark:text-slate-50 tracking-tight leading-none">
                Clinical Consultation Report
              </h1>
              
              {/* Session indices metadata */}
              <div className="flex flex-wrap items-center gap-y-2 gap-x-4 text-xs sm:text-sm text-slate-500 dark:text-slate-400 font-medium">
                <div className="flex items-center gap-1.5 shrink-0">
                  <Calendar className="h-4 w-4 text-slate-400" />
                  <span>{new Date(consultation?.createdAt || Date.now()).toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" })}</span>
                </div>
                <div role="separator" className="hidden sm:block h-3 w-px bg-slate-300 dark:bg-slate-700"></div>
                <div className="flex items-center gap-1.5 shrink-0">
                  <User className="h-4 w-4 text-slate-400" />
                  <span>{consultation?.doctorType || "General Expert"}</span>
                </div>
                <div role="separator" className="hidden sm:block h-3 w-px bg-slate-300 dark:bg-slate-700"></div>
                <div className="flex items-center gap-1.5 shrink-0">
                  <Clock className="h-4 w-4 text-slate-400" />
                  <span>04:15 min audio loop</span>
                </div>
              </div>
            </div>

            {/* Urgency Badge Status Card node */}
            <div className="flex flex-col items-start md:items-end justify-center shrink-0">
              <div className="text-[10px] sm:text-[11px] font-bold text-slate-400 dark:text-slate-500 uppercase tracking-widest mb-1.5">
                Urgency Level Assessed
              </div>
              <div className={`px-4 py-2 rounded-2xl border text-sm font-extrabold tracking-wide uppercase ${urgencyColors} shadow-sm select-none`}>
                {urgencyLabel}
              </div>
            </div>
          </div>
        </motion.div>

        {/* SECTION CARDS staggered grids in visual order */}
        <div className="grid grid-cols-1 gap-6">

          {/* Card 1 — Patient Complaint (Teal Left Border) */}
          <ReportSection 
            title="Patient Complaint" 
            icon={<Activity className="h-5 w-5 text-teal-600" />} 
            borderColor="border-teal-500"
          >
            <div className="italic text-slate-700 dark:text-slate-300 bg-slate-50 dark:bg-slate-800/40 p-4 rounded-xl border border-slate-100 dark:border-slate-800/50">
              "{consultation?.symptoms || "High fever with throbbing headache."}"
            </div>
          </ReportSection>

          {/* Card 2 — Consultation Summary (Blue Left Border) */}
          <ReportSection 
            title="Consultation Summary" 
            icon={<FileText className="h-5 w-5 text-blue-600" />} 
            borderColor="border-blue-500"
          >
            <p className="text-slate-700 dark:text-slate-300 antialiased">
              {report.summary}
            </p>
          </ReportSection>

          {/* Card 3 — Symptoms Identified (Purple Left Border) */}
          <ReportSection 
            title="Symptoms Identified" 
            icon={<Compass className="h-5 w-5 text-purple-600" />} 
            borderColor="border-purple-500"
          >
            <div className="flex flex-wrap gap-2">
              {report.symptomsIdentified.length > 0 ? (
                report.symptomsIdentified.map((symptom, idx) => (
                  <span 
                    key={idx}
                    className="px-3.5 py-1.5 bg-purple-50 text-purple-700 dark:bg-purple-950/30 dark:text-purple-300 border border-purple-200/40 dark:border-purple-900/30 rounded-xl text-xs font-bold"
                  >
                    {symptom}
                  </span>
                ))
              ) : (
                <span className="text-slate-400 italic">No localized clinical indicator found.</span>
              )}
            </div>
          </ReportSection>

          {/* Card 4 — Possible Conditions (Amber Left Border) */}
          <ReportSection 
            title="Possible Conditions" 
            icon={<ShieldQuestion className="h-5 w-5 text-amber-600" />} 
            borderColor="border-amber-500"
          >
            <div className="space-y-3.5">
              <div className="flex items-center gap-2 p-2 px-3 rounded-lg bg-amber-50/50 dark:bg-amber-950/20 text-amber-805 dark:text-amber-400 text-xs font-semibold border border-amber-200/30 select-none">
                <AlertTriangle className="h-4 w-4 text-amber-500 shrink-0" />
                <span className="italic">Provisional summary only — Not a rigorous diagnosis list.</span>
              </div>
              <ul className="space-y-2 border-t border-slate-150/45 dark:border-slate-800/40 pt-3">
                {report.possibleConditions.map((condition, idx) => (
                  <li key={idx} className="flex items-start gap-2.5 text-slate-700 dark:text-slate-300">
                    <span className="h-1.5 w-1.5 rounded-full bg-amber-400 mt-2 shrink-0"></span>
                    <span>{condition}</span>
                  </li>
                ))}
              </ul>
            </div>
          </ReportSection>

          {/* Card 5 — Medications Mentioned (Green Left Border) */}
          <ReportSection 
            title="Suggested OTC Relief & Aids" 
            icon={<Pill className="h-5 w-5 text-emerald-600" />} 
            borderColor="border-emerald-500"
          >
            {report.medicationsSuggested && report.medicationsSuggested.length > 0 ? (
              <div className="space-y-4">
                <div className="overflow-x-auto rounded-xl border border-slate-100 dark:border-slate-800/70 shadow-sm">
                  <table className="min-w-full divide-y divide-slate-100 dark:divide-slate-800/65 font-sans table-auto text-left">
                    <thead className="bg-slate-50 dark:bg-slate-800/40 text-slate-500 dark:text-slate-400 text-[11px] font-bold tracking-widest uppercase select-none">
                      <tr>
                        <th className="px-4 py-3">Medication</th>
                        <th className="px-4 py-3">Primary Purpose</th>
                        <th className="px-4 py-3">Prescription & Safety Note</th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-slate-100 dark:divide-slate-800/60 bg-white dark:bg-slate-900 text-xs sm:text-sm text-slate-700 dark:text-slate-300">
                      {report.medicationsSuggested.map((med, idx) => (
                        <tr key={idx} className="hover:bg-slate-50/50 dark:hover:bg-slate-800/20 transition-all">
                          <td className="px-4 py-3 font-bold text-slate-900 dark:text-slate-100 shrink-0">{med.name}</td>
                          <td className="px-4 py-3 font-medium">{med.purpose}</td>
                          <td className="px-4 py-3 text-slate-500 dark:text-slate-400 leading-relaxed font-sans">{med.note}</td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
                <p className="text-[11px] leading-relaxed text-slate-400 italic">
                  *Check labels carefully. Refrain from taking any chemicals without double checking allergic reactions and counter-indicators.
                </p>
              </div>
            ) : (
              <p className="text-slate-400 italic">No specific medications suggested or discussed during voice flow.</p>
            )}
          </ReportSection>

          {/* Card 6 — Recommendations (Teal Left Border) */}
          <ReportSection 
            title="Actionable Next Steps" 
            icon={<HelpCircle className="h-5 w-5 text-teal-600" />} 
            borderColor="border-teal-500"
          >
            <ol className="space-y-4">
              {report.recommendations.map((rec, idx) => (
                <li key={idx} className="flex gap-3">
                  <div className="flex items-center justify-center h-6 w-6 rounded-full bg-teal-50 dark:bg-teal-950/45 text-teal-700 dark:text-teal-400 text-xs font-bold border border-teal-200/20 shrink-0 select-none">
                    {idx + 1}
                  </div>
                  <span className="text-slate-700 dark:text-slate-300 pt-0.5">{rec}</span>
                </li>
              ))}
            </ol>
          </ReportSection>

          {/* Card 7 — Rest & Lifestyle Advice (Emerald Left Border) */}
          <ReportSection 
            title="Rest & Lifestyle Guidance" 
            icon={<Heart className="h-5 w-5 text-emerald-600" />} 
            borderColor="border-emerald-500"
          >
            <p className="text-slate-700 dark:text-slate-300 leading-relaxed antialiased">
              {report.restAdvice}
            </p>
          </ReportSection>

          {/* Card 8 — When to See a Doctor (Red Left Border) */}
          <ReportSection 
            title="Recommended Clinical Oversight" 
            icon={<HeartHandshake className="h-5 w-5 text-rose-600" />} 
            borderColor="border-rose-500"
          >
            <div className="space-y-3.5">
              <div className="flex flex-col sm:flex-row gap-3">
                <div className="shrink-0 flex items-start">
                  <div className="px-3.5 py-1.5 rounded-xl text-xs font-extrabold border border-rose-200 bg-rose-50 text-rose-700 dark:bg-rose-950/30 dark:text-rose-400 dark:border-rose-900/30 uppercase tracking-wider select-none text-center">
                    Level Assessed: {urgencyLabel}
                  </div>
                </div>
                <p className="text-slate-700 dark:text-slate-300 pt-1 leading-relaxed">
                  {report.followUpAdvise}
                </p>
              </div>
            </div>
          </ReportSection>

        </div>

        {/* DISCLAIMER BOX (Amber background warning banner) */}
        <motion.div 
          initial={{ opacity: 0, y: 10 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="p-5 sm:p-6 bg-gradient-to-r from-amber-500/10 to-orange-500/10 dark:from-amber-950/20 dark:to-orange-950/20 rounded-3xl border border-amber-500/20 dark:border-amber-900/30"
        >
          <div className="flex gap-4">
            <div className="text-amber-500 dark:text-amber-400 mt-0.5 shrink-0 select-none">
              <ShieldAlert className="h-6 w-6 animate-pulse" />
            </div>
            <div className="space-y-1 overflow-hidden">
              <h4 className="font-sans font-bold text-xs sm:text-sm text-slate-800 dark:text-slate-200 tracking-tight leading-none">
                Automated Clinical Intake Disclaimer
              </h4>
              <p className="text-xs text-slate-500 dark:text-slate-400 leading-relaxed antialiased">
                {report.disclaimer}
              </p>
            </div>
          </div>
        </motion.div>

        {/* BOTTOM NAVIGATION ACTION */}
        <div className="flex justify-center pt-4">
          <button
            onClick={onBackToDashboard}
            className="px-8 py-3.5 bg-gradient-to-r from-teal to-teal-dark hover:from-teal-dark hover:to-teal-darker text-white font-bold rounded-2xl text-xs uppercase tracking-widest cursor-pointer shadow-md transition-all hover:-translate-y-0.5 active:translate-y-0 text-center"
          >
            Acknowledge & Return to My Dashboard
          </button>
        </div>

      </div>
    </div>
  );
}
